Travis
avelino/cover.run pull request #12
Opened 2018-05-02 18:15 UTC by bnkamalesh

- Minor cleanup
- Added tests
- added config for travis

2018-05-02 18:46 UTC, avelino requested changes

2018-05-02 18:46 UTC, avelino commented on main.go
> +var (
Group `var`s declarete

2018-05-02 18:46 UTC, avelino commented on main_test.go
> +func TestRun(t *testing.T) {
Create negative case, where you receive a tag that does not exist

What `run()` behavior?

2018-05-02 20:18 UTC, bnkamalesh commented on main_test.go
> +func TestRun(t *testing.T) {
[![](https://travis-ci.org/bnkamalesh/cover.run.svg?branch=master)](https://travis-ci.org/bnkamalesh/cover.run)

Negative tests added.

2018-05-03 09:38 UTC, avelino requested changes

2018-05-03 09:38 UTC, avelino commented on main_test.go
> +// func TestRepoLatest(t *testing.T) {
removed comment source

2018-05-03 12:57 UTC, avelino approved these changes
LGTM

2018-05-03 12:57 UTC, merged

2018-05-03 12:59 UTC, bnkamalesh commented
@avelino, silly me forgot to add the Travis badge on README!